service: suz

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

package:
  include:
    - node_modules/**
  excludeDevDependencies: true

functions:
  menu:
    handler: handler.menu
    events:
      - http:
          path: menu
          method: post
          cors: true
  list:
    handler: handler.list
    events:
      - http:
          path: list 
          method: get
          cors: true
  balance:
    handler: handler.balance
    events:
      - http:
          path: balance
          method: post
          cors: true